name: eosdart
description: EOSIO-based blockchain RPC API client in Dart language
version: 0.4.10
homepage: https://github.com/primes-network/eosdart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0
  pointycastle: ^3.9.1
  eosdart_ecc: ^0.4.4
#  path: ^1.4.1

dependency_overrides:
  eosdart_ecc:
    git:
      url: https://github.com/ms-dehghani/eosdart_ecc
      ref: dev/update_dep

dev_dependencies:
  test: ^1.19.2
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
